### PR TITLE
Ensure we only process true Arrays and Objects - This fixes keys with Date values

### PR DESCRIPTION
**Pull request by MechJosh0**
Fixes https://github.com/rhalff/dot-object/issues/15 and extended current test to include testing Date formats.

### CODE REVIEW

**Comment by rhalff** [comment]
Thanks, seems one of the builds is failing, however if you update the dependencies the error goes away.
I use https://www.npmjs.com/package/npm-check-updates to do this.

`ncu -a && npm update`

Then just also add the updated package.json to the pull request.

**Comment by rhalff** [comment]
Nevermind, I'll do that :)

**Comment by MechJosh0** [comment]
No problem, thanks for solving the build process.

**Comment by rhalff** [comment]
Pushed a new released with your changes, thanks for fixing it.

**Pull request merged**
